/**
 * @license
 * Copyright 2020 Carles Ferrando Garcia (ferrando_cariga@gva.es)
 * SPDX-License-Identifier: BSD-3-Clause
 */

var MSG = {
    title: "S4E",
    btnMinimize: "minimize",
    btnMaximize: "maximize",
    btnClose: "close application",
    blocks: "Bloques",
    prog: "Program",
    catLogic: "Lógica",
    catLoops: "Bucles",
    catMath: "Matemáticas",
    catText: "Texto",
    catLists: "Listas",
    catColour: "Color",
    catVariables: "Variables",
    catFunctions: "Funciones",
    listVariable: "lista",
    textVariable: "texto",
    screenshot: "Descarga una captura de pantalla",
    xmlError: "Imposible de cargar el fichero guardado. Tal vez ha estado creado con otra versión de S4E ?",
    xmlLoad:"Queréis reemplazar los bloques actuales ?\n 'Anula los fusionará.",
    badXml: "Error de análisis XML:\n%1\n\nSelecciona 'De acuerdo' para abandonar los cambios o 'Cancela' para continuar editando el fichero.",
    languageSpan: "escoge idioma",
    levelSpan: "skill level",
    skill1_menu_span: "novice (padawan)",
    skill2_menu_span: "skilled (knight)",
    skill3_menu_span: "expert (master)",
    interfaceColorSpan: "interface theme",
    codeEditorColorSpan: "code editor theme",
    themeSpan: "escoge tema",
    renderSpan: "escoge renderizador",
    fullScreenButton_span: "full screen",
    fullToolboxButton_span: "shrink/expand toolbox",
    blocksPictureButton_span: "show/hide pictures in blocks",
    undoButton_span: "Deshaz",
    redoButton_span: "Rehaz",
    boardButtonSpan: "list boards",
    verifyButton_span: "Verifica código",
    serialButtonSpan: "list COM port",
    uploadButton_span: "Carga",
    serialConnectButton_span: "monitoring & control",
    serialMonitorButton_span: "Serial monitor",
    nodeRedFlowButton_span: "node-Red flows",
    supervisionButton_span: "supervision",
    saveCodeButton_span: "Exporta código Arduino",
    menuButton_span: "File menu",
    newButton_span: "Proyecto nuevo",
    save_span: "Save file name?",
    sketch_name_default: "sketch name",
    sketch_name_wrapper: "project sketch name",
    saveXMLButton_span: "Guarda fichero S4E",
    loadXMLfakeButton_span: "Carga fichero S4E",
    loadXML_span: "Replace existing blocks?\n'Cancel' will merge.",
    loadXML_error_span: "Error parsing XML:\n",
    resetButton_span: "Restablece S4E",
    resetQuestion_span: "Reset S4E and",
    helpButton_span: "ayuda",
    helpModalSpan_title: "Help / About",
    helpModalSpan_text: '<img src="./S4E/media/logo_only.png" alt="" style="height:100px; float:left; margin: 0 10px 10px 0;" />' +
        '<p style="text-align: left;">Designed for <a href="https://www.arrowhead.eu/arrowheadtools" rel="nofollow"><strong>Arrowhead</strong> Tools Project</a>, S4E is a <strong>web-based visual programming editor for <a href="https://www.st.com" rel="nofollow">STmicroelectronics</a></strong> boards, thanks to <a href="https://developers.google.com/blockly/" rel="nofollow">Blockly</a>, the web-based, graphical programming editor.</p>' +
        '<p style="text-align: left;">STudio4Education provides static type language blocks and code generators for simple C programming.</p>' +
        '<p style="text-align: left;">Accessibility: <a href="https://github.com/A-S-T-U-C-E/STudio4Education#accessibility">online documentation</a>.</br>' +
        'Wiki : <a href="https://github.com/A-S-T-U-C-E/STudio4Education/wiki">on Github</a>.</br>' +
        'A bug? Post it here: <a href="https://github.com/A-S-T-U-C-E/STudio4Education/issues">on Github</a>.</br>' +
        'Thanks & libraries: <a href="https://github.com/A-S-T-U-C-E/STudio4Education/wiki/Thanks">on Github</a>.</p>' +
        '<p style="text-align: center;">v0.9.1 - BSD3 license - Sébastien CANET' +
        '<p style="text-align: center;"><a href = (https://www.paypal.com/fr/cgi-bin/webscr?cmd=_flow&SESSION=o8z3KNFl16Tjlxhk1mBekCcRsG_3_NDe0CfWh8b1vfSYIbMxJnwa92YwM3y&dispatch=5885d80a13c0db1f8e263663d3faee8d4fe1dd75ca3bd4f11d72275b28239088">Thanks for donation with Paypal to help me improve this software.</br><img src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donateCC_LG.gif" alt="Paypal"/></a></p>',
    //menu tools
    toolsButton_span: "tools",
    wiringButton_span: "wiring",
    circuitjsButton_span: "circuitJS simulator",
    factoryButton_span: "block factory",
    htmlButton_span: "HTML factory",
    colorConversionButton_span: "colors encoding",
    dataConversionButton_span: "data encoding",
    //menu IoT
    iotConnectButton_span: "servers",
    launchRedServer_span: "Node-RED server",
    launchWebServer_span: "local server",
    papyrusConnect_span: "Papyrus connect",
    papyrusConnect_helper_span: "Papyrus configuration",
    papyrusConfiguration_id_span: "ID of download service",
    papyrusConfiguration_name_span: "name of config file",
    papyrusConfiguration_save_span: "save information",
    ArrowheadConfiguration_helper_span: "Arrowhead configuration",
    ArrowheadConfiguration_span: "connect as provider to Arrowhead cloud",
    ArrowheadConfiguration_span_menu: "Arrowhead connect",
    ArrowheadConfiguration_ServReg_span: "Configure service registry",
    ArrowheadConfiguration_provider_span: "Configure provider",
    ArrowheadConfiguration_consumer_span: "Configure consumer",
    ArrowheadConfiguration_auth_span: "Define authorization server",
    ArrowheadConfiguration_orch_span: "Define orchestrator server",
    blynkConnect_span: "Blynk connect",
    serialConnectIOT_span: "connect serial to IoT",
    //monaco code editor
    editorDiffToggle_span: "compare code modifications",
    copyCodeButton_span: "Copia código a  portapapeles",
    openCodeButton_span: "Open code editor",
    copyConsoleButton_span: "copy console to clipboard",
    cleanConsoleButton_span: "clean console content",
    //lateral panel
    highlightSpan: "highlights the content on the workspace",
    minimapSpan: "(de)activate minimap",
    accessibilitySpan: "habilita modo accesibilidad",
    defaultCursorSpan: "Cursor por defecto",
    basicCursorSpan: "Cursor básico",
    lineCursorSpan: "Cursor linia",
    keyMappingSpan: "abre asignaciones de teclado",
    themeClassicSpan: "Clásico",
    themeModernSpan: "Moderno",
    themeDeuteranopiaSpan: "Deuteranopia/Protanopia",
    themeTritanopiaSpan: "Tritanopia",
    themeZelosSpan: "Zelos",
    themeHighContrastSpan: "Alto contraste",
    themeDarkSpan: "Oscuro",
    themeBwSpan: "Negro & Blanco",
    compilationInProgress: "Placa",
    keyMappingModalSpan: "Establece asignaciones de teclado",
    detailedCompilation_span: "Compilación detallada con mensajes",
    CLI_title_span: "Configura compiler",
    installBoard_title_span: "instala placa al CLI",
    searchlLib_title_span: "busca una biblioteca",
    installLib_title_span: "instala biblioteca  al CLI",
    actionName0: "previo",
    actionName1: "siguiente",
    actionName2: "entra al bloque",
    actionName3: "sal del bloque",
    actionName4: "inserte",
    actionName5: "marca",
    actionName6: "desconecta",
    actionName7: "Caja de herramientas",
    actionName8: "salida",
    actionName9: "mueve el espacio de trabajo arriba",
    actionName10: "mueve el espacio de trabajo abajo",
    actionName11: "mueve el espacio de trabajo a izquierda",
    actionName12: "mueve el espacio de trabajo a derecha",
    actionName13: "conmuta el teclado de navegación",
    setup_sideButton_span: "configura",
    setup_reset_button_span: "reset configuration",
    setup_save_button_span: "save configuration",
    setup_load_button_span: "load configuration",
    config_UI_title_span: "interface",
    displaySpan: "display choice",
    displayChoiceButtons: "buttons only",
    displayChoiceBandT: "buttons + text",
    displayChoiceText: "text only",
    fontSpan: "font choice",
    fontSizeSpan: "renderización",
    optionFontSizeBlocks: "Tamaño del tipo de letra bloques",
    optionFontSizeEditor: "Editor Font Size",
    optionFontSizePage: "Tamaño del tipo de letra página",
    optionFontSpacingPage: "Espaciado de letra página",
    //CLI_functions.js
    CLI_githubLinkButton_span: "documentación",
    coreUpdateButton_msg: "Se está actualizando...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    cleanCLIcacheButton_msg: "Se está limpiando...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    cleanCLIcacheButton_error_msg: "Error suprimiendo la carpeta .\\tmp",
    cleanCLIcacheButton_success_msg: "Limpiado!",
    listBoardsButton_msg: "Se está buscando la placa...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    installBoardsButton_msg: "Se está instalando el soporte de la placa, espera...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    searchlLibButton_msg: "Se está buscando la biblioteca...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    installLibButton_msg: "Se está instalando la biblioteca...\n<i class='fa fa-spinner fa-pulse fa-1_5x fa-fw'></i>",
    coreUpdateButton_span: "actualiza núcleo y bibliotecas",
    cleanCLIcacheButton_span: "Se está limpiando caché",
    listBoardsButton_span: "detección y listado de placas",
    installBoardsInput_span: "nombre de la placa a soportar",
    installBoardsButton_span: "instala este tipo de placa",
    searchlLibInput_span: "nombre de la biblioteca a buscar",
    searchlLibButton_span: "busca esta biblioteca",
    installLibInput_span: "nombre de la biblioteca a instalar",
    installLibButton_span: "instala esta biblioteca",
    //categories panel
    categories_title_span: "categories choice",
    categories_content_selectAll_span: "ALL / NONE",
    categories_search_placeholder: "Search for category...",
    //IoT panel
    iot_title_span: "IoT control",
    ArrowheadConfiguration_helper_span: "Arrowhead configuration",
    //modals
    boardListModalHeader_span: "Boards list",
    boardListModalButton_span: "Details",
    boardModal_connect: "Connector",
    boardModal_voltage: "Operating voltage",
    boardModal_voltage_normal: "Operating voltage (recommended)",
    boardModal_voltage_maxi: "Operating voltage (limits)",
    boardModal_cpu: "Microcontroler µC",
    boardModal_speed: "Clock speed",
    boardModal_inout: "Number of logical I/Os",
    boardModal_in_analog: "Number of analogue I/Os",
    boardModal_out_analog: "Number of PWM ouput",
    boardModal_i_max_out: "Max. current per pin (5V)",
    boardModal_i_max3: "Max. output current on pin 3.3V",
    boardModal_i_max_5: "Max. output current on pin 5V",
    boardModal_flash: "Flash memory",
    boardModal_sram: "SRAM memory",
    boardModal_eeprom: "EEPROM",
    portListModalHeader_span: "COMM port list",
    editorMonacoModal_titlebar: "Code editor",
    editorMonacoModal_undo_span: "undo code modifications",
    editorMonacoModal_redo_span: "redo code modifications",
    editorMonacoModal_diff_span: "open difference pane with original code",
    editorMonacoModal_ok_span: "validate modification to code",
    editorMonacoModal_cancel_span: "reset code panel with original code",
    circuitJSmodalTitle_titlebar: "electronic circuit simulator",
    circuitJSmodal_run: "compile and run code simulation",
    circuitJSmodal_stop: "stop simulation",
    //IDE_functions.js
    IDE_connect: 'Connect to port ',
    IDE_select_port: 'Select a port !',
    IDE_select_board: 'Select a board !',
    IDE_verif_progress: '\nVerification: in progress...\n<i class="fa fa-spinner fa-pulse fa-1_5x fa-fw"></i>',
    IDE_verif_ok: '\nVerification: OK',
    IDE_upload1: 'Board ',
    IDE_upload2: ' on port ',
    IDE_upload3: '\nupload: in progress...\n<i class="fa fa-spinner fa-pulse fa-1_5x fa-fw"></i>',
    IDE_upload_ok: '\nupload: OK',
    serialModalTitle_titlebar_span: 'Serial monitor',
    inputTextSerial: 'Text',
    btn_serialSend_span: 'Send',
    btn_serialConnect_span: 'Start',
    btn_serialStop_span: "Stop",
    btn_serialPeekClear_span: 'Clean',
    btn_serialAddTimeStamp_span: 'Timestamp',
    btn_serialPeekCSV_span: 'Export CSV',
    btn_serialPeekJSON_span: 'Export JSON',
    btn_serialChart_span: 'Graph',
    btn_serialChartPause_span: 'Pause',
    btn_serialChartStart_span: 'Restart',
    btn_serialChartMin_span: 'Min.',
    btn_serialChartMax_span: 'Max.',
    btn_serialChartNb_span: 'Nb.',
    input_serialChartJSONheaders_span: 'JSON headers (;)'
};